# Application Name
# spring:
#   application:
#     name: JPA_Operation  # Application name

# Server Configuration
server:
  port: 8080  # Server port, change if necessary

# Database Configuration for MySQL
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb   # MySQL database URL (replace 'mydb' with your actual database name)
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root        # Your MySQL username
    password: root        # Your MySQL password
    hikari:
      maximum-pool-size: 10  # Optional: Configure connection pool size (optional)

  # Security Configuration
#  security:
#    user:
#      name: Akash          # Username for default user login
#      password: Akash@0202  # Password for default user login
  #   roles: USER         # Role for default user login (commented out)

  # JPA and Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: update    # Automatically creates/updates the database schema
    show-sql: true        # Show SQL queries in the console/logs
    properties:
      hibernate:
        format_sql: true  # Format SQL queries in a readable manner
